version: '2'
services:
  nginx:
    container_name: filestore-nginx
    image: nginx:alpine
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/var/www/html"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
    ports:
      - '9999:80'
  php:
    build: images/php
    container_name: filestore-php
    restart: always
    volumes:
      - "./conf/:/usr/local/etc/php/conf.d/"
      - "./public:/var/www/html"
